# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have a recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend \
"

# This folder should only contains specific patches to fix issue on oe recipes
# Note that these patches may be pushed on Community
BBFILES += "${LAYERDIR}/oe-core/recipes-*/*/*.bbappend"

# This folder should only contains direct backport from oe recipes
# These recipes may be suppress at next update on oe version
BBFILES += "${LAYERDIR}/oe-backport/recipes-*/*/*.bb \
            ${LAYERDIR}/oe-backport/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "myir-openstlinux"
BBFILE_PATTERN_myir-openstlinux := "^${LAYERDIR}/"
BBFILE_PRIORITY_myir-openstlinux = "5"

LAYERDEPENDS_myir-openstlinux = " "
# dependency with meta-networking for netperf, ntp
LAYERDEPENDS_myir-openstlinux += " networking-layer "
# dependency with meta-webserver for netdata
LAYERDEPENDS_myir-openstlinux += " webserver "
# dependency with meta-gnome for stsprof
LAYERDEPENDS_myir-openstlinux += " gnome-layer "
# dependency with meta-multimedia for gstreamer dependency (faac)
LAYERDEPENDS_myir-openstlinux += " multimedia-layer"

# Set a variable to get the openstlinux location
OPENSTLINUX_BASE = "${LAYERDIR}"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_myir-openstlinux = "1"
LAYERSERIES_COMPAT_myir-openstlinux = "scarthgap"

INHERIT += "check-myir-openstlinux-compatibility"
# OpenSTLinux compatibility version
ST_OSTL_COMPATIBILITY_VERSION_myir-openstlinux = "6.1"
